### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by davecrumbacher** [076923/aws-lambda-python-opencv-layer#1]
Can you share the instructions you followed to build these layers? In particular I'm interested in the specific packages you had to include.

**Comment by 076923** [comment]
See `https://pip.pypa.io/en/stable/cli/pip_install/` .

Install to a directory using the **-t** tag and zip.

For creating and sharing a lambda layer, see `https://docs.aws.amazon.com/en_es/lambda/latest/dg/configuration-layers.html`
